name: Bash Linting

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  BashLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Shell Check
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck
      - name: Lint with Shell Check
        run: |-
          cd $GITHUB_WORKSPACE/AI
          git ls-files | grep 'sh$' | xargs shellcheck -x --source-path=SCRIPTDIR
