name: PyLint

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  PythonLinting:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing with pylint
        run: |
          cd $GITHUB_WORKSPACE/AI
          git ls-files | \
          grep 'py$' | \
          xargs pylint --unsafe-load-any-extension=y \
            --disable=fixme,import-error,consider-using-f-string;
